service: saas-messaging-api

provider:
    name: aws
    region: us-east-1   
    runtime: php-82-fpm # تأكد أن الـ GitHub Actions وجهازك مضبوطان على PHP 8.2
    environment:
        APP_ENV: production
        APP_DEBUG: 'true'
        APP_KEY: ${{env:APP_KEY}} # سيقوم بقراءة المفتاح مباشرة من بيئة الـ Deployment الممررة

plugins:
    - ./vendor/bref/bref

functions:
    # دالة معالجة الـ API وتوجيه الروابط بالكامل لارافل
    api:
        handler: public/index.php
        description: 'SaaS Messaging API Gateway'
        timeout: 28 # الحد الأقصى الافتراضي للـ API Gateway بالأمازون
        events:
            - httpApi: '*'