name: Deploy SaaS API via Bref to AWS

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
        extensions: ctype, json, mbstring, openssl, xml, zip, pdo_mysql

    - name: Install Composer Dependencies
        run: composer install --prefer-dist --no-ansi --no-interaction --no-progress --no-scripts --no-dev
    - name: Clear Laravel caches
      run: php artisan config:clear && php artisan cache:clear && php artisan view:clear
    - name: Install Serverless Framework
      run: npm install -g serverless@3

    - name: Deploy to AWS
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        APP_KEY: "base64:Un2ZW/JaX0MmnI8eELjRdBQJG0sDJO+9p1XHOnvGNks="
      run: serverless deploy